version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/change-manifest-src"
    schedule:
      interval: "monthly"
