services:
  web:
    build: .
    ports:
      - "8080"
  scan:
    image: "public.ecr.aws/portswigger/dastardly:latest" 
    environment:
      - BURP_START_URL=http://web:8080
      - BURP_REPORT_FILE_PATH=dastardly-report.xml
      - user=root
    volumes: 
      - .:/dastardly
    depends_on:
      - web


 