services:
  web:
    build: .
    ports:
      - "8080"
  scan:
    image: 'ghcr.io/zaproxy/zaproxy:stable'
    args:
      - zap-full-scan.py
      - -t http://web:8080
    depends_on:
      - web


 
