services:
  web:
    build: .
    ports:
      - "8080"
  scan:
    build: ./dastardly
    environment:
      - BURP_START_URL=http://web:8080
      - user=root
    volumes: 
      - .:/usr/local/burpsuite_enterprise/dastardly2
    depends_on:
      - web


 
