name: build-main

on:
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pasient0
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: |
          docker build . -t pasient0/simple-server:${{ github.sha }}-signed
      - uses: sigstore/cosign-installer@main
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.PRIVATE_KEY_MAIN }}
      - name: Sign the published Docker image
        run: cosign sign --key cosign.key pasient0/simple-server@$(docker images --no-trunc --quiet pasient0/simple-server) -y
      - name: push image
        run: docker push pasient0/simple-server:${{ github.sha }}-signed
