name: build-main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pasient0
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build . -t pasient0/simple-server
      - uses: sigstore/cosign-installer@main
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.PRIVATE_KEY_MAIN }}
        
      - name: Sign the published Docker image
        run: cosign sign --key cosign.key pasient0/simple-server@"$SHA256" -y
        env:
          SHA256: $(docker images --no-trunc --quiet pasient0/simple-server)
      - name: push image
        run: docker push pasient0/simple-server@"$SHA256" 
        env:
          SHA256: $(docker images --no-trunc --quiet pasient0/simple-server)
