name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pasient0
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build . -t pasient0/simple-server:latest
      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.0.0
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_KEY }}
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: cosign sign --key cosign.key pasient0/simple-server:latest
      - name: push image
        run: docker push pasient0/simple-server:latest 
