name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  create_key_pair:
    runs-on: ubuntu-latest
    steps:
      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.0.0
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.PRIVATE_KEY_MAIN }} 
