name: security:scan
on: [pull_request]
    
# Declare default permissions as read only.
permissions: read-all

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | 
          docker-compose -f compose.yml up --abort-on-container-exit --exit-code-from scan

