name: security scan main
on:
  push:
    branches: [ "main" ]
    
# Declare default permissions as read only.
permissions: read-all

jobs:
  ossf_analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - name: "Checkout ossf code"
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          persist-credentials: false
      - name: "Run analysis"
        uses: ossf/scorecard-action@e38b1902ae4f44df626f11ba0734b14fb91f8f86 # v2.1.2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac4f944fd5 # v2.2.4
        with:
          sarif_file: results.sarif
  owasp-zap-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | 
          docker-compose -f compose.yml up --abort-on-container-exit --exit-code-from scan

