name: security scan main
on:
  push:
    branches: [ "main" ]

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | 
          docker-compose -f compose.yml up --abort-on-container-exit --exit-code-from scan
          ls -la
          cd .. && ls -la 
      - name: Archive scan results 
        uses: actions/upload-artifact@v3
        with:
          name: dastardly-report
          path: /dastardly/dastardly-report.xml

